export const sample_foods: any[] = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: '/assets/images/foods/food-img-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    cookTime: '20-30',
    price: 20,
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: '/assets/images/foods/food-img-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    cookTime: '10-15',
    price: 5,
    favorite: false,
    origins: ['us', 'germany'],
    stars: 3.5,
    imageUrl: '/assets/images/foods/food-img-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    cookTime: '15-20',
    price: 2,
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: '/assets/images/foods/food-img-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    cookTime: '40-50',
    price: 11,
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: '/assets/images/foods/food-img-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Humburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shangai',
    isAdmin: false,
  },
];
